### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by htmlcoder1562** [Inqbus/braille_radio#1]
In PyPi, it doesn't say anything about _***how***_ to use it.

**Comment by volkerjaenisch** [comment]
If you have followed the installation, just run "bradio" or "braille_radio" on the command line.
Then please follow the instructions on screen. 

The screen consists of two lines. Usually on the first line the operation takes place and on the second line there is additional information e.g. the help.

At the first start bradio will load the list of available radio stations this can take several minutes, so please stay tuned.  

If you type "r" followed by "s" you will go to the "search area". Here you simply type ahead and the  virtual "list" of matching stations will be displayed. Going up/down will "scroll" thru the "list".  Hit enter and a station is played. Hit ESC and you cancel the last operation or go back one level in the "menu".

**Comment by htmlcoder1562** [comment]
You should show it in the instructions on PyPI.

**Comment by volkerjaenisch** [comment]
Will do

**Comment by htmlcoder1562** [comment]
Thanks!
